# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Rocamora Asesores
email: your-email@domain.com
author: Your Name
description: ROCAMORA ASESORES

copyright: 'Copyright &copy; 2018 ROCAMORA. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://es.linkedin.com/company/rocamora-asesores
